### PR TITLE
Feature/people service

### PR DESCRIPTION
**Pull request by chuanlin2018**
1. Applied people service to author and point of contact components.
2. Made url parameters case insensitive. The motivation is: while testing locally, sometime I mistype "editEnabled" with "editenabled" and the page won't work and it took me a while to figure out the problem. 

To test, 
1. Run backend oar-pdr-py (branch: feature/people-index)
2. Angular: Turn on fake backend to bypass the authentication and run.
    Test url: http://localhost:4202/od/id/test2?editenabled=true

### CODE REVIEW

**Review by RayPlante — CHANGES_REQUESTED** [review]
I'm seeing the following build error:
```
libs/oarlps/src/lib/landing/author/author-edit/author-edit.component.ts:65:17 - error TS2551: Property 'getOrgs' does not exist on type 'StaffDirectoryService'. Did you mean 'getOrg'?

65         this.ps.getOrgs().subscribe({
                   ~~~~~~~

  ../lib/dist/oarng/lib/staffdir/staffdir.service.d.ts:155:5
    155     getOrg(id: number): Observable<anyobj | null>;
            ~~~~~~
    'getOrg' is declared here.
```
Perhaps something didn't get fully pushed?

**Comment by chuanlin2018** [comment]
My bad. I added getOrgs() in lib to get the existing list of organizations in order to create the dropdown list of affiliation. Later on we decided not to use the dropdown but I forgot to remove the function. And I didn't check in the code in oar-lib-angular.
Just removed the function.

**Review by RayPlante — CHANGES_REQUESTED** [review]
I tested this under oar-docker locally, and I found a few issues:
1. When filling in affiliation subunits automatically from the people service data, please:
     1.  restrict it to the 3 most specific organizational units (i.e. the first three returned by the service),
     1.  reverse the order that they appear so that the OU appears first, group last.
2.  Sometimes when I type in the people lookup box, no results come up or sometimes the results are known to be incomplete.  In particular, I noticed:
     1.  If I type 3 or more characters rapidly, no results come up; if I then type 2 characters and then pause, matching suggestions come up.
     1.  Sometimes it appears that if I type in a few characters, but then erase them, and then type in new characters, the list that comes up is either empty or incomplete.

Item (2) may be a bug in the `StaffDirectoryService` implementation or in how it is used by the LPS.  I can help with debugging this.

**Comment by chuanlin** [comment]
The above two issues are fixed.

**Review by RayPlante — APPROVED** [review]

**Pull request merged**
