### PR TITLE
Support m1 builds, clean-up build scripts

### PR DESCRIPTION
**Pull request by RayPlante**
This PR combines a number updates to the package's build scripts but which should not have any effect on the content of the actual built applications (but which require corresponding changes to oar-docker).  One key goal is to support builds for Macs featuring the m1 processor.  Changes include:
*  replace separate docker build containers `wizard` and `editable` with a single `build-test` container
*  uprev the gosu version used in the docker-based build (needed for m1 builds)
*  change distribution names, `wizard` and `editable` to `midas-author-wizard` and `midas-author-lps`
*  replace separate `makedist.editable` and `makedist.wizard` scripts with single `makedist` script
*  streamline docker-based build scripts
*  address some dependency vulnerabilities reported by `npm audit`

To test:
  1.  check out this branch
  2.  run `docker/dockbuild.sh` and ensure that it completes successfully
  3.  run `scripts/makedist.docker` and ensure that it completes successfully
  4.  ensure that the `dist` directory contains distributions (zip files and `_dep.json` files) with base names, `midas-author-wizard` and `midas-author-lps`

### CODE REVIEW

**Comment by chuanlin2018** [comment]
I got this error while running scripts/makedist.docker. When I check the code, I found that the lib folder was empty. Seems oar-lib-angular was not copied over for some reason:

+ npm run build-lib

> build-lib
> npm run build oarng --prefix ./lib

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /dev/oar-pdr-angular/lib/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/dev/oar-pdr-angular/lib/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/developer/.npm/_logs/2023-09-01T15_42_14_835Z-debug-0.log

**Comment by chuanlin2018** [comment]
This is how I pull oar-lib-angular into oar-pdr-angular manually:
cd oar-pdr-angular/
git submodule update --init --recursive
cd lib
git checkout integration

**Comment by RayPlante** [comment]
@chuanlin2018 Can you try this test again after having run the `git submodule` command?

**Comment by chuanlin2018** [comment]
Tested. Saw zip files and _dep.json files under dist folder.
Should I merge it?

**Comment by RayPlante** [comment]
Merged in fix/docker-cacerts to this before merging to feature/metadata-editing-auth.

**Pull request merged**
