### PR TITLE
Fix/keyword undo

### PR DESCRIPTION
**Pull request by chuanlin2018**
This check in fixed following problem:

If there is no keyword in original record, after add some keywords and undo, the value still stay in the memory.

### CODE REVIEW

**Comment by RayPlante** [comment]
Note that this branch extends #50.

**Comment by chuanlin2018** [comment]
Oh yes. #50 can be closed actually.

**Comment by chuanlin2018** [comment]
I believe the undo problem was fixed. I tested locally using mdsdev as backend.

**Review by RayPlante — APPROVED** [review]
The last commit fixes the crash-on-undo problem with references that I reported; for this reason I'm approving this.  I'm seeing at least one other bug, though: once when I had two references and tried to re-edit the second one, the form would bring up the first one.  

The lack of DOI resolution is a noticeable issue.  We'll have to revisit this.

**Pull request merged**
