### PR TITLE
Feature/collection from pdr

### PR DESCRIPTION
**Pull request by chuanlin2018**
This checkin merged collection page and tool menu from oar-pdr into oar-pdr-angular.

To test locally, turn on the fake backend in app.module.ts then use following urls:

Regular page:
http://localhost:4202/od/id/test2?editMode=revise
CHIPS collection page: 
http://localhost:4202/od/id/pdr0-0002?editMode=revise
Forensics page: 
http://localhost:4202/od/id/pdr0-0001?editmode=revise

### CODE REVIEW

**Review by RayPlante — CHANGES_REQUESTED** [review]
I'm seeing a page loading failure when running under oar-docker.  Please address the following:
  * resolve conflicts indicated on this PR page (by merging integration into this branch)
  * test under oar-docker.  I recommend using the `MIDASbeta` branch
  * remove console debug messages that no longer serve a purpose; in particular, remove message that prints token to console.

**Comment by chuanlin2018** [comment]
Conflicts resolved and console log cleaned up. Local run successfully.
But when I did docker local deploy, I got problem while building npsbroker:
===
#########################
#
# Building npsbroker...
#
#########################
+ mkdir -p /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/build/oar/usnistgov/oar-midas-portal/0.1.0rc5/oar-midas-portal/python/build/npsbroker
+ cp /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/build/oar/usnistgov/oar-midas-portal/0.1.0rc5/oar-midas-portal/python/nps_server/nps_broker.py /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/build/oar/usnistgov/oar-midas-portal/0.1.0rc5/oar-midas-portal/python/build/npsbroker/nps_broker.py
+ cd /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/build/oar/usnistgov/oar-midas-portal/0.1.0rc5/oar-midas-portal/python/build
+ zip -qr /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/build/oar/usnistgov/oar-midas-portal/0.1.0rc5/oar-midas-portal/dist/npsbroker-portal.zip npsbroker
+ set +x
Created distribution in dist directory:
npsbroker-portal.zip
# archiving npsbroker-portal.zip -> npsbroker.zip
# installing auth-py into authbroker/.
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-auth-py/1.0.1rc1/auth-py.zip -> /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/authbroker
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-auth-py/1.0.1rc1/auth-py_dep.json -> authbroker
# installing oar-config-server into midasconfigserver/.
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-config/MIDASbeta/oar-config-server.jar -> /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/config
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-config/MIDASbeta/oar-config-server_dep.json -> config
# installing midas-portal into ngapps/built/portal
+ unzip -oq /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-midas-portal/0.1.0rc5/midas-portal.zip
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-midas-portal/0.1.0rc5/midas-portal_dep.json -> ngapps
# installing dmp-ui into ngapps/built/dmpui
+ unzip -oq /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-dmp-angular-ui/0.1.0rc8/dmp-ui.zip
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-dmp-angular-ui/0.1.0rc8/dmp-ui_dep.json -> ngapps
# installing midas-author-lps into ngapps/built/dapui
+ unzip -oq /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-pdr-angular/feature/collection-from-pdr/midas-author-lps.zip
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-pdr-angular/feature/collection-from-pdr/midas-author-lps_dep.json -> ngapps
# installing midas-author-wizard into ngapps/built/dapui
+ unzip -oq /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-pdr-angular/feature/collection-from-pdr/midas-author-wizard.zip
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-pdr-angular/feature/collection-from-pdr/midas-author-wizard_dep.json -> ngapps
# installing pdr-py into dbio/.
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-pdr-py/fix/fm-x509-auth/pdr-py.zip -> /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/dbio
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-pdr-py/fix/fm-x509-auth/pdr-py_dep.json -> dbio
# installing nextcloud-api into nextcloud/.
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/nextcloud-api/oar-docker-x509/nextcloud-api.zip -> /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/filemanager/nextcloud
localdeploy: nextcloud: No _dep.json file found for nextcloud-api
# installing fm-application-layer into fmapp/.
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-fm-application-layer/oar-docker-x509/fm-application-layer.zip -> /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/filemanager/fmapp
localdeploy: fmapp: No _dep.json file found for fm-application-layer
# installing npsbroker into npsbroker/.
# copy /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/archive/oar/usnistgov/oar-midas-portal/0.1.0rc5/npsbroker.zip -> /Users/lnc9/Documents/Code/docker_test/oar-docker/midas/npsbroker
localdeploy: npsbroker: No _dep.json file found for npsbroker
+ /Users/lnc9/Documents/Code/docker_test/oar-docker/scripts/setversion.sh
===

**Comment by chuanlin2018** [comment]
I also cleaned up oar-lib-angular to stop printing token to the console. PR#30 created and assigned to you.

**Comment by RayPlante** [comment]
Testing under oar-docker, it appears that the portal will be need to be updated to link to existing drafts using URL noted in this PR description--namely, to use `?editMode=revise` instead of `?enableEdit=true`.  The latter results in an error from the angular code.

**Comment by chuanlin2018** [comment]
This branch is good to go.

**Comment by RayPlante** [comment]
@chuanlin2018 On the landing page, the label for keywords appears to be "Subject keywords: Keywords:".  Do you see this, too?

**Comment by chuanlin2018** [comment]
Fixed.

**Review by RayPlante — APPROVED** [review]

**Pull request merged**
